### ISSUE TITLE
feat: Output continuously

### ISSUE THREAD

**Issue by shunkakinoki** [ph-fritsche/scripts#2]
**Is your feature request related to a problem? Please describe.**
Is there a way to emit output simultaneously while running code?

**Describe the solution you'd like**
Right now, output is emitted after exit. I would like to know if there can be options to output the console continuously.

**Describe alternatives you've considered**

**Additional context**
Thanks for this wonderful repo, was looking for something like it!!!

**Comment by ph-fritsche** [comment]
I'm glad you can make use of it :smiley: 

The package does not handle the output. It just resolves the script name to an import, prepares the arguments and calls the function.

If you write e.g. to `process.stdout` in your script, it is just as if you write to it when executing the script directly per `node`.
With the following config `yarn scripts write-continously` should output every second to the console:
```js
// scripts.config.js
module.exports = {
    scripts: {
        'write-continously': {
            async run() {
                for (let i = 0; i < 10; i++) {
                    process.stdout.write(`${i}... `)
                    await new Promise(res => setTimeout(res, 1000))
                }
            },
        },
    },
}
```

If it doesn't, there is some buffering happening between node and your console that is not the default behavior.
If it does, your script buffers it's output itself somewhere and just writes on exit.
